### ISSUE TITLE
On insert mode, the cursor will be before the character

### ISSUE THREAD

**Issue by ioRekz** [tednaleid/sublime-EasyMotion#27]
I only use a subset of vim navigation functionality so I'm really often in "insert" mode.

Then when I want to easy motion to a character, the cursor will be just before the character I want to, and in my case, I almost always want to go after this character.

Any idea how I can do it ?

**Comment by pruppert** [comment]
How do I get into insert mode? I am also wanting the cursor to go after the character I chose. FYI, I am on ST3.
