### ISSUE TITLE
Have you seen AceJump?

### ISSUE THREAD

**Issue by gbbr** [tednaleid/sublime-EasyMotion#51]
Just some feedback: Personally I think it takes too much concentration and it becomes a distraction away from work the fact that you have to press "Enter" to move on to the next batch of results. I use my monitor vertically and there is always a lot of code visible, if I choose to jump to letter "A" which is quite common, I might have to press Enter up to 3 times to get to it. This has made me stopped using EasyMotion as much as I would like too.

What I'd like to suggest is an approach similar to AceJump (which I am using with IntelliJ) where if there are more results than letters it switches into a mode where you can press 2 letters instead of one to jump further up. This way you could allow much higher coverage. If I were more proficient in Python I would add this myself but I am not. 

I think this is worth considering and I would personally love this plugin if you would add this feature. I'm attaching an example of AceJump from IntelliJ below. It is uglier than EasyMotion but just to make a point.

Thanks!

![screen shot 2014-09-17 at 11 31 16](https://cloud.githubusercontent.com/assets/6686356/4302034/9950196a-3e55-11e4-8f74-d4468ed6ef60.png)

**Comment by tednaleid** [comment]
An AceJump plugin for ST3 has been released, I'd check that out: https://github.com/ice9js/ace-jump-sublime

**Comment by eorroe** [comment]
Pretty confusing how to set up, I'm not sure if like it said copying the contents actually works. Also I have to set the syntax to acejump??
